version: 2
jobs:
  test:
    docker:
      - image: circleci/node:4.8.2-jessie
    steps:
      - checkout
      - run:
          name: Compile
          command: npm run truffle-compile
      - run:
          name: Migrate
          command: npm run truffle-migrate
      - run:
          name: Test
          command: npm run truffle-test

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
